server:
  port: 8001 #服务端口号
spring:
  application:
    name: userServer  #微服务名称，对外暴漏的微服务名称，十分重要
  ################################################## JDBC 通用配置  ##########################################
  datasource:
    username: yy123456        #数据库登陆用户名
    password: Yy123456        #数据库登陆密码
    url: jdbc:mysql://wanenggod.mysql.rds.aliyuncs.com:3306/wanenggod?useSSL=false&serverTimezone=Asia/Shanghai       #数据库url
    driver-class-name: com.mysql.jdbc.Driver                  #数据库驱动

############################### 不检查 spring.config.import=configserver:##################
#  cloud:
#    config:
#      enabled: false
###################################### MyBatis 配置 ######################################
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.xinqiu.api.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
     # spring boot集成mybatis的方式打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
########################################### Spring cloud 自定义服务名称和 ip 地址###############################################
eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址 （单机版）

  instance:
    instance-id: USER-8001 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址
########################################## spring cloud 使用 Spring Boot actuator 监控完善信息###################################
# Spring Boot 2.50对 actuator 监控屏蔽了大多数的节点，只暴露了 heath 节点，本段配置（*）就是为了开启所有的节点
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: user
  company.name: com.xinqiu.user
  build.aetifactId: @project.artifactId@
  build.version: @project.version@

pagehelper:
  helper-dialect: mysql # 指定数据库	可以不配置，插件会自动检测数据库的类型
  reasonable: true #分页合理化 当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  support-methods-arguments: true
  pageSizeZero: false #为true时，第零页显示全部
  params: count=countSqls